import { Card } from './card';

export const CARDS: Card[] = [
    { id: '0', name: 'A'},
    { id: '1', name: 'B'},
    { id: '2', name: 'C'},
    { id: '3', name: 'D'},
    { id: '4', name: 'E'},
    { id: '5', name: 'F'},
    { id: '6', name: 'G'},
    { id: '7', name: 'H'},
    { id: '8', name: 'I'},
    { id: '9', name: 'J'},
    { id: '10', name: 'K'},
	{ id: '11', name: 'L'},
	{ id: '12', name: 'M'},
	{ id: '13', name: 'N'},
	{ id: '14', name: 'O'},
	{ id: '15', name: 'P'},
	{ id: '16', name: 'Q'},
	{ id: '17', name: 'R'},
	{ id: '18', name: 'S'},
	{ id: '19', name: 'T'},
	{ id: '20', name: 'U'},
	{ id: '21', name: 'V'},
	{ id: '22', name: 'W'},
	{ id: '23', name: 'X'},
	{ id: '24', name: 'Y'},
	{ id: '25', name: 'Z'},
];
export const CARDS2: Card[] = [
    { id: '0', name: 'Anteater'},
    { id: '1', name: 'Bear'},
    { id: '2', name: 'Camel'},
    { id: '3', name: 'Dog'},
    { id: '4', name: 'Elephant'},
    { id: '5', name: 'Frog'},
    { id: '6', name: 'Giraffe'},
    { id: '7', name: 'Hippo'},
    { id: '8', name: 'Iguana'},
    { id: '9', name: 'Jaguar'},
    { id: '10', name: 'Kangaroo'},
	{ id: '11', name: 'Lion'},
	{ id: '12', name: 'Meercat'},
	{ id: '13', name: 'Newt'},
	{ id: '14', name: 'Ostrich'},
	{ id: '15', name: 'Panda'},
	{ id: '16', name: 'Quetzal'},
	{ id: '17', name: 'Rhinoceros'},
	{ id: '18', name: 'Sheep'},
	{ id: '19', name: 'Tiger'},
	{ id: '20', name: 'Uakaris'},
	{ id: '21', name: 'Vampire Bat'},
	{ id: '22', name: 'Whale'},
	{ id: '23', name: 'X-Ray Tetra'},
	{ id: '24', name: 'Yak'},
	{ id: '25', name: 'Zebra'},
 ];